# Generated by Django 3.1 on 2022-09-14 23:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220903_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', help_text='Maximum file size allowed is 2Mb', null=True, upload_to='images/'),
        ),
    ]
