# Generated by Django 3.1 on 2022-09-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220915_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', help_text='Ukuran maksimal gambar 2 MB', null=True, upload_to='images/'),
        ),
    ]
