# Generated by Django 3.1.4 on 2022-09-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220816_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='judul',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='penulis',
            field=models.CharField(default='admin', max_length=15),
        ),
    ]
