# Generated by Django 3.1 on 2022-09-14 23:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220915_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='gambar',
            field=models.ImageField(default='images/default.png', help_text='Please use our recommended dimensions: 2 MB MAX', upload_to='blog/', validators=[blog.models.ImageValidator(size=2000000)]),
        ),
    ]
