# Generated by Django 3.1.4 on 2022-08-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220831_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='first_name',
            new_name='kota',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='town_city',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='userbase',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
