# Generated by Django 3.1.4 on 2022-08-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220831_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='kota',
        ),
    ]
