# Generated by Django 3.1.4 on 2022-09-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220831_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='about',
            field=models.TextField(blank=True, max_length=300, verbose_name='about'),
        ),
    ]
